### ISSUE TITLE
Imagemagick 7 is not available on Ubuntu or Debian

### ISSUE THREAD

**Issue by blaueente** [slhck/compress-pptx#3]
The readme lists

> ImageMagick's magick, which calls convert and identify

which makes it clear that Imagemagick 7 is required, as only this version introduces the "magick" command, instead of directly exposing "convert" and "identify".

> Under Ubuntu, get ImageMagick via:
> apt install imagemagick

This is clearly wrong and insufficient, as debian, and therefore ubuntu has not yet packaged version 7
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929825

Installing Imagemagick from source is usually discouraged, as it has a lot of dependencies. Additionally having an image parser, getting security support from the distribution is rather important. 

Preferred solution: Make compatible with Imagemagick version 6.
It is unclear how easy it would be to make compress-pptx compatible with version 6, I suspect that minor changes in the calling command line could be sufficient.

Workaround: change documentation.

**Comment by slhck** [comment]
You're right about this; I just didn't think about Linux support in that way because it'd be rare to find someone using PPTX files there.

I made the script use `convert` and `identify` again. Could you perhaps test with IM 6? I don't have it available here at the moment.
